// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '#',
    appId: '1:649346244475:web:864b82451c48a0c889a7de',
    messagingSenderId: '649346244475',
    projectId: 'presensi-dinkop',
    authDomain: 'presensi-dinkop.firebaseapp.com',
    storageBucket: 'presensi-dinkop.firebasestorage.app',
    measurementId: 'G-Q2Q9VV7R9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '#',
    appId: '#',
    messagingSenderId: '649346244475',
    projectId: 'presensi-dinkop',
    storageBucket: 'presensi-dinkop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '#',
    appId: '1:649346244475:ios:bea3df732c02999289a7de',
    messagingSenderId: '649346244475',
    projectId: 'presensi-dinkop',
    storageBucket: 'presensi-dinkop.firebasestorage.app',
    iosBundleId: 'com.example.presensiDinkop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '#',
    appId: '1:649346244475:ios:bea3df732c02999289a7de',
    messagingSenderId: '649346244475',
    projectId: 'presensi-dinkop',
    storageBucket: 'presensi-dinkop.firebasestorage.app',
    iosBundleId: 'com.example.presensiDinkop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '#',
    appId: '1:649346244475:web:4264a339a90507c089a7de',
    messagingSenderId: '649346244475',
    projectId: 'presensi-dinkop',
    authDomain: 'presensi-dinkop.firebaseapp.com',
    storageBucket: 'presensi-dinkop.firebasestorage.app',
    measurementId: 'G-RCVQBLPBK0',
  );

}
